import random,time
a = input(">>>").split('+,-')
for i in a:
    s=tuple(i)
    print(s)
x = random.randint(1,6)
y = random.randint(1,6)
z = random.randint(1,6)
print("正在摇奖.....")
time.sleep(1)
print("正在摇奖.....")
time.sleep(1)
print("正在摇奖.....")
time.sleep(1)
print("第一个数字是: %d "% x)
print("正在摇奖.....")
time.sleep(1)
print("正在摇奖.....")
time.sleep(1)
print("正在摇奖.....")
time.sleep(1)
print("第二个数字是: %d "% y)
print("正在摇奖.....")
time.sleep(1)
print("正在摇奖.....")
time.sleep(1)
print("正在摇奖.....")
time.sleep(1)
print("第三个数字是: %d "% z)
print(" %d  %d  %d" % (x,y,z))
